# Generated by Django 6.1 on 2026-08-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_category_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Tech', 'Tech'), ('Makeup & Beauty', 'Makeup & Beauty'), ('Clothing', 'Clothing'), ('Shoes', 'Shoes'), ('Food', 'Food'), ('Games', 'Games'), ('Home', 'Home'), ('Accessories', 'Accessories'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
