# Generated by Django 6.1 on 2026-08-29 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Tech', 'Tech'), ('Makeup & Beauty', 'Makeup & Beauty'), ('Clothing', 'Clothing'), ('Shoes', 'Shoes'), ('Food', 'Food'), ('Games & Toys', 'Games & Toys'), ('Home', 'Home'), ('Accessories', 'Accessories'), ('School Supplies', 'School Supplies'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=30)),
                ('icon', models.CharField(choices=[('flower', '🌸 Flower'), ('butterfly', '🦋 Butterfly'), ('fish', '🐟 Fish'), ('star', '⭐ Star'), ('car', '🚗 Car'), ('zebra', '🦓 Zebra'), ('hourglass', '⏳ Hourglass'), ('ant', '🐜 Ant'), ('horse', '🐴 Horse'), ('camel', '🐪 Camel')], default='flower', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
